### ISSUE TITLE
Symfony 4?

### ISSUE THREAD

**Issue by theDyingMountain** [heimrichhannot/contao-encore-bundle#1]
Can you add "symfony/framework-bundle": "3.4.* || 4.1.*" as dependency or are there any problems with symfony 4?

**Comment by Defcon0** [comment]
Hello,

I removed it as dependency since it also comes with the contao composer.json. We didn't test it with symfony 4, yet, but it would be great if you could test it in your symfony 4.x project.

**Comment by theDyingMountain** [comment]
thx for updating your composer.json, but i got the following error on cache:warmup after install with composer:
`   In ExtensionSet.php line 146:
Unable to register extension "Symfony\WebpackEncoreBundle\Twig\EntryFilesTw
    igExtension" as it is already registered.`

**Comment by koertho** [comment]
@Defcon0 Could be a problem with this line? 
https://github.com/heimrichhannot/contao-encore-bundle/blob/a1461c9313d546753bf7102c785860fa14db9247/src/ContaoManager/Plugin.php#L28

@theDyingMountain Na hallo! ;-)
Hast du möglicherweise das [Symfony Webpack Encore Bundle](https://github.com/symfony/webpack-encore-bundle) schon über eine andere Erweiterung/Bundle im Symfony Kernel registriert?

**Comment by theDyingMountain** [comment]
@koertho Hiho ;-)
Habe gerade nochmal in die composer.json geschaut. Da gibt es kein weiteres Bundle, was diese Encore Bundle als Abhängigkeit hat.

**Comment by koertho** [comment]
@theDyingMountain Welche Contao- und Symfony-Version setzt du ein?

**Comment by theDyingMountain** [comment]
@koertho Contao 4.6 und PHP 7.2
Könnt ihr den Fehler nicht reproduzieren?

**Comment by Defcon0** [comment]
@theDyingMountain Ist es die Managed-Version von Contao 4.6? Also hast du dir die Version mit Composer so geholt:

```
php composer.phar create-project contao/managed-edition <ziel> '4.6.*'
```

Davon hängt ab, wie wir das ganze reproduzieren können :-) Wir arbeiten nur mit LTS-Versionen, daher haben wir das ganze bisher nur mit 4.4 getestet. Wenn wir es aber auch für 4.6 fit bekommen, um so besser ;-)

**Comment by theDyingMountain** [comment]
@Defcon0 Ne nicht über composer direkt sondern über den contao-manager in einer lokalen devilbox docker umgebung.

**Comment by koertho** [comment]
@theDyingMountain Probiere mal bitte Version 0.8.1, ich denke wir haben den Fehler gefunden.

**Comment by theDyingMountain** [comment]
@koertho Jep mit Version 0.8.1 hat es funktioniert :)
