### ISSUE TITLE
Proposal: Use default contao template fields

### ISSUE THREAD

**Issue by koertho** [heimrichhannot/contao-encore-bundle#15]
We should use replaceDynamicScriptTags Hook in combination with [[TL_BODY]], [[TL_CSS]], [[TL_HEAD]] to insert encore assets instead of using our own template variables. So this bundle would be easier to use and need no changes to the default fe_page template.

Possible Roadmap:
1. add ´use_contao_script_tags` config with default value false
2. if set to true, these will be used instead of our own template variables
3. in version 2.0 this option will set to true by default (or removed in combination with our own template tags)

Disadvantage:
- the hook just pass the buffer, no other context variables -> in contao 4.9 we have the page object in the request, so we could use this. For 4.4 we could drop the support in version 2.0 or add the page object before (if not already there, this must be checked)

Links:
https://docs.contao.org/dev/reference/hooks/replaceDynamicScriptTags/

**Comment by koertho** [comment]
@Defcon0 What do you think?

**Comment by Defcon0** [comment]
If you have the needed context there, then definitely. When I was building the initial version of encore bundle, I didn't know the hook. Of course it's better to not having to change the fe_page :-)

Thanks!
