### ISSUE TITLE
Bug: Insertion of fe_page_encore_bundle on Contao-Preview

### ISSUE THREAD

**Issue by Xendiadyon** [heimrichhannot/contao-encore-bundle#24]
**Context**
Contao version: 4.13.14
Bundle version: 1.17.3
PHP version: 7.4.30

**Description**
When using the Contao preview function, under certain conditions the fe_page_encore_bundle can not be inserted into the fe_page.
Instead, the square brackets appear in the source code:
![grafik](https://user-images.githubusercontent.com/2657385/204524224-7bb16e27-462a-4539-9090-73a1f95476d6.png)

To review the issue, I created a preview link of a blog post. Hence, the issue is identical for my preview (logged in) and the customer preview (link with hash):
https://christian-methfessel.de/_contao/preview/5?_hash=rDt5YoK2N30k93mhpGk4ftJrCrCvdF0%2Fb7VGMX0KurM%3D

The (existing) page https://christian-methfessel.de/musiker/panfloete/ratgeber/stimmen-der-panfloete/ should be opened.
Instead, only the loading animation is shown (which would stop being there when the CSS files would be correctly loaded. If you peek beneath this div, you will notice that no js/css files were inserted by encore).

It seems that this issue only exists on some of my special blog detail pages, such as everything in /agile-coach/ and /musiker/panfloete/ .
On all the other pages and on my "basic blog" https://christian-methfessel.de/blog/ladeanimation-selbst-gemacht/ everything works fine.

So there is quite a chance that this issue is not easily reproducible.
If you need further insights, you can contact me and I give you full access to my development server.

Thanks!

**Comment by Xendiadyon** [comment]
I got two steps further and can lead you to the source of the problem:

1. You need two different news archives
![grafik](https://user-images.githubusercontent.com/2657385/204536546-f96dbaa6-a5f7-4238-8d8c-d762349cfe3f.png)

2. On the news detail page, you need two different news reader modules, each showing the content of a separate news archive.

3. Now, if you open a news detail page, Contao will always throw a 404 page (because there will never be two news entries in both news archives with an identical alias). This is expected behavior and you can reproduce it in the demo using two news archives and two newsreader modules: https://demo.contao.org/en/news-detail/new-contao-versions-in-short-intervalls.html
![grafik](https://user-images.githubusercontent.com/2657385/204537054-5344fcd4-6f77-460a-8174-680ed4dd5a84.png)

4. However in this (admittedly very special) case, this encore-bundle does not correctly parse the ``[[HUH_ENCORE_CSS]]`` and thus there is no CSS and JS inserted via encore.

I am quite positive that you can reproduce this issue now. But if you have further questions, feel free to contact me.

**Comment by koertho** [comment]
Hi, thanks for reporting the issue. I hope I fixed it in version 1.17.4
