### ISSUE TITLE
Feature: make bundle compatible for Contao 5.x

### ISSUE THREAD

**Issue by Baloobear** [heimrichhannot/contao-encore-bundle#29]
Hello,

I'm not sure if this bundle might be still useful for Contao 5.x since it uses twig templates by itself (which makes your twig support bundle obsolete, at least).

If this bundle still might be useful (which I hope) there's no chance to use this bundle with Contao 5.x, since it depends on PHP 8.1.

Are there any plans (resp. quick workarounds available) to do any upgrade of this bundle to let it work with Contao 5.x?

Otherwise, If this bundle is obsolete are there any sources where to get some docs to let Encore work properly with Contao 5.x?
Unfortunately I haven't found any docs for the current Contao version since nearly all docs relate to Contao 4.x.

Thanks.

**Comment by koertho** [comment]
Hi, I think you throw together two bundles, this bundle have nothing to do with twig support in contao ;)
And this bundle is already compatible with php 8.1, if you find an specific issue, please report it.
Sure, we want to make this bundle compatible with contao 5 in the future, but we can't promise a soon support, as we only work with contao lts versions, so contao 5 is not on out priority list. 

For encore support in contao 5, you can currently only use encore directly and contao also has a basic encore support build in, see https://docs.contao.org/dev/framework/asset-management/#accessing-assets-in-templates (it is a little hidden in the docs). But you won't have the extended features of encore bundle available currently.

**Comment by Baloobear** [comment]
Hi @koertho,

sorry for my misleading description regarding the use of twig templates in this bundle. It was absolutely clear for me that this bundles purpose is not to include twig templates into Contao.

Despite that it's good to know that you'll plan to support Contao 5.x in the future and I can understand that you'll mainly support the LTS versions of Contao. Although it's sad for me now since I cannot use assets versioning without an increasing development process.

Thanks

**Comment by koertho** [comment]
Sure, I currently working in my private time on allowing contao 5 for this bundle, since I want to use it in a private project. Unfortunately this is a lot of work on some dependencies so I can't give you a time frame, but I hope to have results soon

**Comment by koertho** [comment]
This bundle is now compatible with contao 5 in 2.0.0-beta.
