### ISSUE TITLE
 Command nicht definiert ? There are no commands defined in the "encore" namespace.

### ISSUE THREAD

**Issue by theDyingMountain** [heimrichhannot/contao-encore-bundle#3]
Ich schon wieder 😉
Wenn ich auf der console encore:prepare aufrufe erhalte ich folgende Meldung:

`There are no commands defined in the "encore" namespace.`

Anscheinend wird das Command nicht definiert bzw. fehlt die commands.yml?

**Comment by koertho** [comment]
Hach :D

Da hat sich wohl wieder etwas im Vergleich zu Symfony 3 geändert, hier werden Commands automatisch registriert, wenn sie im Command Namespace liegen. Müssen wir mal schauen.

**Comment by theDyingMountain** [comment]
Anscheinend. 🤔
Wenn ich eine commands.yml anlege so wie im Core, funktioniert es.

**Comment by koertho** [comment]
@theDyingMountain Ich schau es mir an, sobald ich dazu komme. Unter Symfony 3 ist das noch nicht notwendig. Echt krass was man an Fehlern wegen Symfony 4 reinbekommt :D

**Comment by koertho** [comment]
@theDyingMountain Sollte nun behoben sein.
