### ISSUE TITLE
ReferenceError: name is not defined in encore.bundles.js

### ISSUE THREAD

**Issue by leonexcc** [heimrichhannot/contao-encore-bundle#5]
I switched from my old Encore setup to your plugin. After installing it, i called `vendor/bin/contao-console encore:prepare` to generate the encore.bundles.js.

If i then execute yarn watch, i get the following error message:

```
ReferenceError: name is not defined
    at Object.name [as addEntries] ([...]/encore.bundles.js:105:14)
    at Object.addEntries ([...]/webpack.config.babel.js:91:15)
```

The code in that line is `for (name in bundles)`. If i change this to `for (let name in bundles)` everything works as expected (`var`would also work). This is probably related to my slightly stricter babel setup.

**Comment by koertho** [comment]
Thanks for reporting!

**Comment by leonexcc** [comment]
Sadly this isn't fixed for me. I just noticed a couple of places where the `let` is missing too:

https://github.com/heimrichhannot/contao-encore-bundle/blob/85e0238dfe3ba7e1c69d4ee8c084f516ae3a343d/src/Resources/views/encore_bundles.js.twig#L38

and the one that was causing the error in my case:

https://github.com/heimrichhannot/contao-encore-bundle/blob/85e0238dfe3ba7e1c69d4ee8c084f516ae3a343d/src/Resources/views/encore_bundles.js.twig#L105

Sorry, for not posting more context above.

**Comment by koertho** [comment]
@leonexcc Sorry, I just overlooked them. Hope I got them all now ;)

**Comment by leonexcc** [comment]
@koertho Works now! Thanks for the quick fix!
