### ISSUE TITLE
Import custom entries from build/entrypoints.json

### ISSUE THREAD

**Issue by leonexcc** [heimrichhannot/contao-encore-bundle#6]
As far as i understand, i have to add all my entries from the webpack.config.js to the config.yml in order to use it in the layout or pages.

Would it be possible to parse the build/entrypoints.json generated by Encore (filter out the babel-polyfill and other duplicates from the config.yml) and show them in addition to the once from the config? The `requiresCss` could be defined by detecting a .css and `head` could be false by default.

This would speed up the usage of this bundle a lot, in my opinion.

**Comment by koertho** [comment]
@leonexcc That looks like an good addition to this bundle, but I'm not shure if can realize this soon, as we don't have this use case in our environments. If you like, you can do a pull request to get this feature sooner :)
