### ISSUE TITLE
encorePublicPath in tl_layout is never used

### ISSUE THREAD

**Issue by leonexcc** [heimrichhannot/contao-encore-bundle#7]
It seems that the encorePublicPath field in tl_layout is never used.

The entries are loaded via the encore_entry_* Twig extensions from the Webpack Encore Bundle, which defines its own output_path.

**Comment by koertho** [comment]
@leonexcc That's maybe a leftover from the time before we integrated the Webpack Encore Bundle. I will remove it.

**Comment by koertho** [comment]
@leonexcc Removed in 1.0.3.
